stages:
  scrape:
    cmd: python -m telex.pipeline.scrape.scraping
      --output-folder "data/raw/raw"
    deps:
      - telex/pipeline/scrape
    outs:
      - data/raw
    params:
      - params.py:
          - MAX_PAGES
          - PER_PAGE
          - SLEEP_TIME
  preprocess:
    cmd: python -m telex.pipeline.preprocess.preprocessing
      --input-folder "data/raw/raw"
      --output-folder "data/preprocessed"
    deps:
      - telex/pipeline/preprocess
      - data/raw
    outs:
      - data/preprocessed

#  preprocess:
#    cmd: python -m telex-nlp.pipeline.preprocess.preprocessing
#      --output-file "data/preprocessed/preprocessed.txt"
#    deps:
#      - telex-nlp/pipeline/preprocess
#    outs:
#      - data/preprocessed
#
#  train:
#    cmd: python -m telex-nlp.pipeline.train.training
#      --preprocessed-file "data/preprocessed/preprocessed.txt"
#      --output-file "data/models/model.txt"
#    deps:
#      - data/preprocessed
#      - telex-nlp/pipeline/train
#    outs:
#      - data/models
#    params:
#      - params.py:
#          - SEED
#
#  evaluate:
#    cmd: python -m telex-nlp.pipeline.evaluate.evaluation
#      --model-file "data/models/model.txt"
#    deps:
#      - data/models
#      - telex-nlp/pipeline/evaluate


