stages:
  scrape:
    cmd: python -m telex.pipeline.scrape.scraping
      --output-folder "data/raw/raw"
    deps:
      - telex/pipeline/scrape
    outs:
      - data/raw
    params:
      - params.py:
          - MAX_PAGES
          - PER_PAGE
          - SLEEP_TIME
  preprocess:
    cmd: python -m telex.pipeline.preprocess.preprocessing
      --input-folder "data/raw/raw"
      --output-folder "data/preprocessed"
    deps:
      - telex/pipeline/preprocess
      - data/raw
    outs:
      - data/preprocessed
  train:
    cmd: python -m telex.pipeline.train.training
      --input-file "data/preprocessed/telex.json"
      --output-folder "data/models"
    deps:
      - telex/pipeline/train
      - data/preprocessed
    outs:
      - data/models
    params:
      - params.py:
          - MODEL
          - VOCAB
          - BigramParams
          - TrainingParams
          - TransformerParams
  evaluate:
    cmd: python -m telex.pipeline.evaluate.evaluation
      --model-file "data/models/model.pt"
      --input-file "data/preprocessed/telex.json"
    deps:
      - telex/pipeline/evaluate
      - data/models
      - data/preprocessed
    params:
      - params.py:
          - MODEL
          - VOCAB
          - BigramParams
          - TrainingParams
          - TransformerParams